const console = require('console')
const {
  util
} = require('./lib/main')

// console.log(util.map([1, 2, 3, 4], a => a + a))
// console.log(util.indexOfElement([1,2,3,4], 2))
// console.log(util.reduce([1, 2, 3, 4], (a, b) => a + b, 0))
// console.log(util.sliceString('hello world', 3))
// console.log(util.reverseArray([1, 2, 3, 4]))
// console.log(util.concatArrays([1, 2, 3], [3, 4, 5]))
// console.log(util.flatten([1, 2, [3, 4, [5, [6], 7], 8], 9], 2))
// console.log(util.isString('hello'))
// console.log(util.flatMap([1, 2, 3, [4, 5], [6]], a => a * a))
// console.log(util.arrayLength([1, 2, 3]))
// console.log(util.arrayLength(12))
// console.log(util.max([1, 2, 100, 'true']))
// console.log(util.trim('    hello         '))
// console.log(util.isEmptyObject({ a: 1 }))
// console.log(util.sliceArray([1, 2, 3, 4, 5, 6], 2, 5))
// console.log(util.hasKey({ a: 1}, 'b'))
// console.log(util.isArray([]))
// console.log(util.isThisNaN({}))
// console.log(util.any([1, 2, 3, 4], a => a % 5 === 0))
// console.log(util.howMany('a b c a d a', 'a'))
// console.log(util.dropFromStart([1, 2, 3, 4], 2))
// console.log(without([1, 2, 3, 4], 1, 2))
// console.log(util.random(12, 30))
